services:
  dotnet-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dotnet-dev
    networks:
      - contextualized-notification-platform
    volumes:
      - .:/contextualized-notification-platform
    command: sleep infinity

networks:
  contextualized-notification-platform:
    driver: bridge