services:
  dotnet-cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: dotnet-cli
    networks:
      - contextualized-notification-platform
    volumes:
      - .:/contextualized-notification-platform

networks:
  contextualized-notification-platform:
    driver: bridge